#!/bin/bash

swaylock \
    --screenshots \
    --clock \
    --indicator \
    --indicator-radius 150 \
    --indicator-thickness 12 \
    --effect-blur 8x6 \
    --ring-color bb00cc \
    --key-hl-color 880033 \
    --line-color 00000000 \
    --inside-color 00000088 \
    --separator-color 00000000 \
    --show-failed-attempts
